### ISSUE TITLE
Question: What would be the best option to have image with latest bazel included

### ISSUE THREAD

**Issue by emartynov** [cirruslabs/docker-images-android#18]
Hi people!

I see that you have both images for android sdk and bazel. What would be the best strategy to have both layers in one image?

A similar question I have for the latest gradle.

**Comment by fkorotkov** [comment]
I think the easiest way will be to use `cirrusci/android-sdk:29` as base and just install Bazel in a separate layer. `Dockerfile` will look like this:

```Dockerfile
FROM cirrusci/android-sdk:29

ENV BAZEL_VERSION 1.0.0

RUN wget -q -O install.sh https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh \
    && chmod +x install.sh \
    && ./install.sh --user \
    && rm -f install.sh

ENV PATH ${PATH}:${HOME}/bin

RUN bazel version
```

If you are using Cirrus CI then you can use [Dockerfile as a CI environment feature](https://cirrus-ci.org/guide/docker-builder-vm/#dockerfile-as-a-ci-environment). Otherwise you'll need to build and push an image to your separate repository.

**Comment by emartynov** [comment]
Thank you!

My hope wat that Cirrus CI will have these combined images. But I think it is too many variations. So I have to build an image myself.

I also found a way to blend two images https://stackoverflow.com/questions/39626579/is-there-a-way-to-combine-docker-images-into-1-container

An amazing feature for the building images! Let me check it closer.

**Comment by fkorotkov** [comment]
Yeah, too many variants to combine in one. Bazel is updating more frequently then Android. Another option might be to add '29-bazel' tag like the Docker file above and update only this image on Bazel releazes.

BTW very exciting to see Bazel is used more in the wild for the Android projects. Out of curiosity, could you please share with any deatils about your project if possible? I used to work on a build system so this area is particularly intriging for me. 😅
