### ISSUE TITLE
Rebuild image

### ISSUE THREAD

**Issue by ZuSe** [cirruslabs/docker-images-android#21]
Hey guys,

as the new v3 API of Google requires at least fastlane in version 2.136 it would be good to push an updated build of this image to dockerhub.

Thanks in advance

Best
Patrick

**Comment by fkorotkov** [comment]
Oh. I think it will make sense actually to remove `fastlane` from the image because it's updating too frequently comparing to the main Android related SDK and packages. 🤔 You'll need to `gem install fastlane -NV` manually or build an image on top of the current ones.
