### ISSUE TITLE
Windows image with Android SDK bundled?

### ISSUE THREAD

**Issue by dnfield** [cirruslabs/docker-images-android#3]
Would it be possible to get a Windows image with the Android SDK bundled?  I'd like to do some integration testing on Windows that will need that.  I could pull it down as part of my process, but it'd be nice if it was just there.

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/pull/27971/files#diff-2b848e82272bc9ad8f2258be9579f014

Seems like trying to use it keeps timing out though...

**Comment by dnfield** [comment]
The last time I updated a docker image for Cirrus, I saw a dependency to build the docker image: https://cirrus-ci.com/task/4615320787484672

But when I'm trying to use the new Windows one I don't see that, and the job just ends up timing out.  I'm trying it with compute credits now to see if that helps anything...

**Comment by fkorotkov** [comment]
@dnfield I'll debug the issue a little bit later. I see the container is starting in Azure but agent is not communicating back. 🤔

**Comment by dnfield** [comment]
I seem to be able to get the Mac to download and Cache the open JDK and Android SDK.  I may just try that approach on Windows as well.

**Comment by fkorotkov** [comment]
And I'm trying to build a Windows image and in parallel debugging the startup issues.

**Comment by dnfield** [comment]
Hmm, it looks like even switching back to the "regular" Cirrus Windows container is not getting past the Triggered stage.  Maybe related to what you're looking at?

**Comment by fkorotkov** [comment]
It seems it's failing to download an agent. `agent.exe` is zero bytes on the agent and startup script just re-tries indefinitely.

**Comment by dnfield** [comment]
(Ignore my last comment, it was a bug in my environment var setup)

**Comment by fkorotkov** [comment]
Created containers in #4. Will wait until they are built and pushed to try on your branch.

**Comment by dnfield** [comment]
Fantastic, thanks!  I'm going to remove the image I made in the meantime since I'm not sure it's working and it's likely to cause confusion if I leave it there.

**Comment by dnfield** [comment]
I've updated my PR - it's fine for it to fail for now until the image is available, I'll check back when it is.

**Comment by dnfield** [comment]
Still getting agent not responding with your images :\ https://cirrus-ci.com/task/5874215791099904

**Comment by fkorotkov** [comment]
I've just checked the container in Azure and it just can't connect to the internet. Not only `api.cirrus-ci.com` but also `google.com`. 😲Very weird. Looking into it...

**Comment by fkorotkov** [comment]
It seems it [can be an issue for an initial short period of time](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-troubleshooting#windows-containers-slow-network-readiness). But the container never gets the internet....

**Comment by fkorotkov** [comment]
Tried on the "secret" `os_version: gcp2016` which uses GCP VMs to run the containers and got:

```
Error starting command: exec: "cmd.exe": executable file not found in %PATH%
```

Will continue looking into later today.

**Comment by fkorotkov** [comment]
Fixing PATH in #6

**Comment by dnfield** [comment]
Ahh that makes sense.

**Comment by dnfield** [comment]
I don't think the licenses are actually accepted in the latest one.

**Comment by fkorotkov** [comment]
@dnfield fixing in #8

**Comment by fkorotkov** [comment]
@dnfield could you please try again? Licenses should be accepted now.

**Comment by dnfield** [comment]
It made it further this time, but still missing some licenses https://cirrus-ci.com/task/5755365288312832

I think `echo y` only gets you the first license - the SDK manager asks you to accept several.

**Comment by dnfield** [comment]
https://github.com/cirruslabs/docker-images-android/pull/9 fixed this!
