### ISSUE TITLE
NDK images

### ISSUE THREAD

**Issue by ened** [cirruslabs/docker-images-android#33]
Turns out the NDK built on in the "30-ndk" image may be _too new_ to be picked up by the current AGP versions.

A detailed table here: https://developer.android.com/studio/projects/install-ndk#default-ndk-per-agp

Should the 30-ndk image therefore:
- contain both the latest NDK versions (21.x & 20.x)
- only contain the NDK which matches the latest stable AGP?
- stay as is

Personally, I'd probably go with the first option (or better, include _every_ latest NDK version), however such image will take up significant space.

**Comment by fkorotkov** [comment]
We can change verison to the one supported by Gradle plugin. Let's just add a link to this page in Dockerfile so it's transparent where the version comes from.
