### ISSUE TITLE
Update to Android SDK 31

### ISSUE THREAD

**Issue by twwd** [cirruslabs/docker-images-android#40]
Hey folks,

Android 12 was released back in September and thus a new SDK version was published too. Could you please build a new image for SDK version 31?

**Comment by fkorotkov** [comment]
Don't see it's updated here https://developer.android.com/studio/releases/build-tools Do you know if 31.0.0 is availble?

**Comment by twwd** [comment]
My fault – I've looked into the wrong changelog 🤦🏻‍♂️ 
Sorry for the inconvenience.

**Comment by fkorotkov** [comment]
No worries. I was also wondering when they'll do a release. Page I referred still claims 30.0.0 is an rc4 from May 🤷
