### ISSUE TITLE
Update focal to jammy

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [cirruslabs/docker-images-android#44]
This docker image still uses Ubuntu 20.04 (focal) as base image. This causes problems together with https://github.com/cirruslabs/docker-images-flutter/blob/master/desktop/linux/Dockerfile, as Ubuntu focal still ships `jsoncpp` version 1. Any other modern distribution including Ubuntu jammy, Debian testing, Fedora or Arch ship `jsoncpp` version 2. All Flutter Linux builds are incompatible with desktop distributions hence.

I'd highly recommend to update to Ubuntu 22.04 LTS (jammy) hence.

**Comment by fkorotkov** [comment]
Next version bump in https://github.com/cirruslabs/docker-images-flutter should pick up the new base. Thank you for bringing this up!
