### ISSUE TITLE
Why is `emulator` installed only on x86_64?

### ISSUE THREAD

**Issue by bartekpacia** [cirruslabs/docker-images-android#62]
Code in question:

https://github.com/cirruslabs/docker-images-android/blob/5419e5d1b56bfdfac7ba665a2dd5f5ffe14a7423/sdk/tools/Dockerfile#L46

**Comment by fkorotkov** [comment]
At the time they were not available on Arm. Do they now?

**Comment by bartekpacia** [comment]
Oh, you're right – it's still not available.

Relevant issue: https://issuetracker.google.com/issues/227219818
