### ISSUE TITLE
Add latest Gradle to the image

### ISSUE THREAD

**Issue by bartekpacia** [cirruslabs/docker-images-android#65]
Gradle is the most popular build tool used in Android. Maybe it'd make sense to use one of the [`gradle`](https://hub.docker.com/_/gradle/) images as base of `android-sdk:tools` instead of `ubuntu:22.04`?

Most projects use a version from `gradle-wrapper.properties` though, so I'm not sure how much sense it makes.

**Comment by fkorotkov** [comment]
I don't think most people use the latest gradle plus we rarely update these images since cadence of Android updates is much slower than Gradle. IMO people should use Gradle Wrapper to make sure they are in control of Gradle Version.
